### ISSUE TITLE
cannot load such file -- treetop (LoadError)

### ISSUE THREAD

**Issue by turboladen** [michaeledgar/laser#16]
I'm running MRI 1.9.3.  I ran `$ gem install laser -v 0.7.0.pre1 --pre` then `$ laser --help` and get:

```
/Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/gems/laser-0.7.0.pre1/lib/laser.rb:26:in `require': cannot load such file -- treetop (LoadError)
from /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/gems/laser-0.7.0.pre1/lib/laser.rb:26:in `<top (required)>'
from /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/gems/laser-0.7.0.pre1/bin/laser:6:in `require'
from /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/gems/laser-0.7.0.pre1/bin/laser:6:in `<top (required)>'
from /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/bin/laser:19:in `load'
from /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/bin/laser:19:in `<main>'
```

I then `$ gem install treetop`, then `$ laser` and still get the same LoadError.

```
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.10
  - RUBY VERSION: 1.9.3 (2011-10-30 patchlevel 0) [x86_64-darwin11.2.0]
  - INSTALLATION DIRECTORY: /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0
  - RUBY EXECUTABLE: /Users/Steveloveless/.rvm/rubies/ruby-1.9.3-p0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-11
  - GEM PATHS:
     - /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0
     - /Users/Steveloveless/.rvm/gems/ruby-1.9.3-p0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => true
     - :bulk_threshold => 1000
     - :sources => ["http://rubygems.org/"]
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - http://rubygems.org/
```

**Comment by turboladen** [comment]
It seems that laser picked up on the Gemfile that was in my current local directory.  I hadn't included laser in the Gemfile yet, so it wasn't finding the treetop dep.  I didn't expect this, so it might be nice to document.  I suppose this isn't a bug though.
