### ISSUE TITLE
"rake build" gives Syck error

### ISSUE THREAD

**Issue by tcopeland** [michaeledgar/laser#9]
Maybe just me?

``` shell
$ rvm info

ruby-1.9.2-p290@laser:

  system:
    uname:       "Darwin tom-mac-2.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:32:41 PDT 2011; root:xnu-1504.15.3~1/RELEASE_X86_64 x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin10.0)"
    zsh:         "/bin/zsh => zsh 4.3.9 (i386-apple-darwin10.0)"

  rvm:
    version:      "rvm 1.7.2 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p290"
    date:         "2011-07-09"
    platform:     "x86_64-darwin10.8.0"
    patchlevel:   "2011-07-09 revision 32553"
    full_version: "ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin10.8.0]"

  homes:
    gem:          "/Users/tom/.rvm/gems/ruby-1.9.2-p290@laser"
    ruby:         "/Users/tom/.rvm/rubies/ruby-1.9.2-p290"

  binaries:
    ruby:         "/Users/tom/.rvm/rubies/ruby-1.9.2-p290/bin/ruby"
    irb:          "/Users/tom/.rvm/rubies/ruby-1.9.2-p290/bin/irb"
    gem:          "/Users/tom/.rvm/rubies/ruby-1.9.2-p290/bin/gem"
    rake:         "/Users/tom/.rvm/gems/ruby-1.9.2-p290@laser/bin/rake"

  environment:
    PATH:         "/Users/tom/.rvm/gems/ruby-1.9.2-p290@laser/bin:/Users/tom/.rvm/gems/ruby-1.9.2-p290@global/bin:/Users/tom/.rvm/rubies/ruby-1.9.2-p290/bin:/Users/tom/.rvm/bin:/usr/local/mysql51/bin/:/usr/local/maven/bin/:/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0//Home/bin/:/Users/tom/bin:/usr/local/apache2/bin/:/usr/local/sphinx/bin/:/usr/local/pgsql/bin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/jmeter/bin/:/Users/tom/ec2-tools/bin/:/usr/local/fop/:/usr/local/ant/bin/:/usr/local/javacc/bin/:/usr/local/jruby/bin/:/Users/tom/src/android-sdk-mac_86/tools/:/Users/tom/src/flex-4.1/bin:/Applications/GitX.app/Contents/Resources/"
    GEM_HOME:     "/Users/tom/.rvm/gems/ruby-1.9.2-p290@laser"
    GEM_PATH:     "/Users/tom/.rvm/gems/ruby-1.9.2-p290@laser:/Users/tom/.rvm/gems/ruby-1.9.2-p290@global"
    MY_RUBY_HOME: "/Users/tom/.rvm/rubies/ruby-1.9.2-p290"
    IRBRC:        "/Users/tom/.rvm/rubies/ruby-1.9.2-p290/.irbrc"
    RUBYOPT:      ""
    gemset:       "laser"

$ rake build --trace
** Invoke build (first_time)
** Execute build
rake aborted!
undefined method `write' for #<Syck::Emitter:0x00000102313a00>
/Users/tom/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/psych/visitors/emitter.rb:17:in `end_document'
/Users/tom/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/psych/visitors/emitter.rb:17:in `visit_Psych_Nodes_Document'
/Users/tom/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/psych/visitors/visitor.rb:10:in `accept'
```

**Comment by suryagaddipati** [comment]
I too get the same error when i do the build
